[Mon Sep 07 05:25:44 2015] [error] [client 108.14.46.233] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/home/demo/demo/app/logs/dev.log" could not be opened: fopen(/home/demo/demo/app/logs/dev.log) [<a href='function.fopen'>function.fopen</a>]: failed to open stream: Permission denied' in /home/demo/demo/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84\nStack trace:\n#0 /home/demo/demo/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /home/demo/demo/vendor/monolog/monolog/src/Monolog/Logger.php(265): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /home/demo/demo/vendor/monolog/monolog/src/Monolog/Logger.php(445): Monolog\\Logger->addRecord(500, 'Uncaught Except...', Array)\n#3 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(490): Monolog\\Logger->log('critical', 'Uncaught Except...', Array)\n#4 [internal function]: Symfony\\Component\\Debug\\ErrorHandler->handleException(Object(UnexpectedValueException) in /home/demo/demo/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 84
[Mon Sep 07 05:25:44 2015] [error] [client 108.14.46.233] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/home/demo/demo/app/logs/dev.log" could not be opened: fopen(/home/demo/demo/app/logs/dev.log) [<a href='function.fopen'>function.fopen</a>]: failed to open stream: Permission denied' in /home/demo/demo/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84\nStack trace:\n#0 /home/demo/demo/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /home/demo/demo/vendor/monolog/monolog/src/Monolog/Logger.php(265): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /home/demo/demo/vendor/monolog/monolog/src/Monolog/Logger.php(445): Monolog\\Logger->addRecord(500, 'Fatal Error: Un...', Array)\n#3 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(490): Monolog\\Logger->log('critical', 'Fatal Error: Un...', Array)\n#4 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(565): Symfony\\Component in /home/demo/demo/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 84
[Mon Sep 07 05:25:55 2015] [error] [client 108.14.46.233] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/home/demo/demo/app/logs/dev.log" could not be opened: fopen(/home/demo/demo/app/logs/dev.log) [<a href='function.fopen'>function.fopen</a>]: failed to open stream: Permission denied' in /home/demo/demo/app/cache/dev/classes.php:5260\nStack trace:\n#0 /home/demo/demo/app/cache/dev/classes.php(5200): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /home/demo/demo/app/cache/dev/classes.php(5647): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /home/demo/demo/app/cache/dev/classes.php(5718): Monolog\\Logger->addRecord(500, 'Uncaught Except...', Array)\n#3 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(490): Monolog\\Logger->log('critical', 'Uncaught Except...', Array)\n#4 [internal function]: Symfony\\Component\\Debug\\ErrorHandler->handleException(Object(UnexpectedValueException))\n#5 {main}\n  thrown in /home/demo/demo/app/cache/dev/classes.php on line 5260
[Mon Sep 07 05:25:55 2015] [error] [client 108.14.46.233] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/home/demo/demo/app/logs/dev.log" could not be opened: fopen(/home/demo/demo/app/logs/dev.log) [<a href='function.fopen'>function.fopen</a>]: failed to open stream: Permission denied' in /home/demo/demo/app/cache/dev/classes.php:5260\nStack trace:\n#0 /home/demo/demo/app/cache/dev/classes.php(5200): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /home/demo/demo/app/cache/dev/classes.php(5647): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /home/demo/demo/app/cache/dev/classes.php(5718): Monolog\\Logger->addRecord(500, 'Fatal Error: Un...', Array)\n#3 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(490): Monolog\\Logger->log('critical', 'Fatal Error: Un...', Array)\n#4 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(565): Symfony\\Component\\Debug\\ErrorHandler->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#5 [inter in /home/demo/demo/app/cache/dev/classes.php on line 5260
[Mon Sep 07 05:27:02 2015] [error] [client 108.14.46.233] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/home/demo/demo/app/logs/dev.log" could not be opened: fopen(/home/demo/demo/app/logs/dev.log) [<a href='function.fopen'>function.fopen</a>]: failed to open stream: Permission denied' in /home/demo/demo/app/cache/dev/classes.php:5260\nStack trace:\n#0 /home/demo/demo/app/cache/dev/classes.php(5200): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /home/demo/demo/app/cache/dev/classes.php(5647): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /home/demo/demo/app/cache/dev/classes.php(5718): Monolog\\Logger->addRecord(500, 'Uncaught Except...', Array)\n#3 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(490): Monolog\\Logger->log('critical', 'Uncaught Except...', Array)\n#4 [internal function]: Symfony\\Component\\Debug\\ErrorHandler->handleException(Object(UnexpectedValueException))\n#5 {main}\n  thrown in /home/demo/demo/app/cache/dev/classes.php on line 5260
[Mon Sep 07 05:27:02 2015] [error] [client 108.14.46.233] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/home/demo/demo/app/logs/dev.log" could not be opened: fopen(/home/demo/demo/app/logs/dev.log) [<a href='function.fopen'>function.fopen</a>]: failed to open stream: Permission denied' in /home/demo/demo/app/cache/dev/classes.php:5260\nStack trace:\n#0 /home/demo/demo/app/cache/dev/classes.php(5200): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /home/demo/demo/app/cache/dev/classes.php(5647): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /home/demo/demo/app/cache/dev/classes.php(5718): Monolog\\Logger->addRecord(500, 'Fatal Error: Un...', Array)\n#3 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(490): Monolog\\Logger->log('critical', 'Fatal Error: Un...', Array)\n#4 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(565): Symfony\\Component\\Debug\\ErrorHandler->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#5 [inter in /home/demo/demo/app/cache/dev/classes.php on line 5260
[Mon Sep 07 05:27:52 2015] [error] [client 108.14.46.233] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/home/demo/demo/app/logs/dev.log" could not be opened: fopen(/home/demo/demo/app/logs/dev.log) [<a href='function.fopen'>function.fopen</a>]: failed to open stream: Permission denied' in /home/demo/demo/app/cache/dev/classes.php:5260\nStack trace:\n#0 /home/demo/demo/app/cache/dev/classes.php(5200): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /home/demo/demo/app/cache/dev/classes.php(5647): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /home/demo/demo/app/cache/dev/classes.php(5718): Monolog\\Logger->addRecord(500, 'Uncaught Except...', Array)\n#3 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(490): Monolog\\Logger->log('critical', 'Uncaught Except...', Array)\n#4 [internal function]: Symfony\\Component\\Debug\\ErrorHandler->handleException(Object(UnexpectedValueException))\n#5 {main}\n  thrown in /home/demo/demo/app/cache/dev/classes.php on line 5260
[Mon Sep 07 05:27:52 2015] [error] [client 108.14.46.233] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/home/demo/demo/app/logs/dev.log" could not be opened: fopen(/home/demo/demo/app/logs/dev.log) [<a href='function.fopen'>function.fopen</a>]: failed to open stream: Permission denied' in /home/demo/demo/app/cache/dev/classes.php:5260\nStack trace:\n#0 /home/demo/demo/app/cache/dev/classes.php(5200): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /home/demo/demo/app/cache/dev/classes.php(5647): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /home/demo/demo/app/cache/dev/classes.php(5718): Monolog\\Logger->addRecord(500, 'Fatal Error: Un...', Array)\n#3 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(490): Monolog\\Logger->log('critical', 'Fatal Error: Un...', Array)\n#4 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(565): Symfony\\Component\\Debug\\ErrorHandler->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#5 [inter in /home/demo/demo/app/cache/dev/classes.php on line 5260
[Mon Sep 07 05:28:09 2015] [error] [client 108.14.46.233] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/home/demo/demo/app/logs/dev.log" could not be opened: fopen(/home/demo/demo/app/logs/dev.log) [<a href='function.fopen'>function.fopen</a>]: failed to open stream: Permission denied' in /home/demo/demo/app/cache/dev/classes.php:5260\nStack trace:\n#0 /home/demo/demo/app/cache/dev/classes.php(5200): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /home/demo/demo/app/cache/dev/classes.php(5647): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /home/demo/demo/app/cache/dev/classes.php(5718): Monolog\\Logger->addRecord(500, 'Uncaught Except...', Array)\n#3 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(490): Monolog\\Logger->log('critical', 'Uncaught Except...', Array)\n#4 [internal function]: Symfony\\Component\\Debug\\ErrorHandler->handleException(Object(UnexpectedValueException))\n#5 {main}\n  thrown in /home/demo/demo/app/cache/dev/classes.php on line 5260
[Mon Sep 07 05:28:09 2015] [error] [client 108.14.46.233] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/home/demo/demo/app/logs/dev.log" could not be opened: fopen(/home/demo/demo/app/logs/dev.log) [<a href='function.fopen'>function.fopen</a>]: failed to open stream: Permission denied' in /home/demo/demo/app/cache/dev/classes.php:5260\nStack trace:\n#0 /home/demo/demo/app/cache/dev/classes.php(5200): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /home/demo/demo/app/cache/dev/classes.php(5647): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /home/demo/demo/app/cache/dev/classes.php(5718): Monolog\\Logger->addRecord(500, 'Fatal Error: Un...', Array)\n#3 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(490): Monolog\\Logger->log('critical', 'Fatal Error: Un...', Array)\n#4 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(565): Symfony\\Component\\Debug\\ErrorHandler->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#5 [inter in /home/demo/demo/app/cache/dev/classes.php on line 5260
[Mon Sep 07 05:28:15 2015] [error] [client 108.14.46.233] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/home/demo/demo/app/logs/dev.log" could not be opened: fopen(/home/demo/demo/app/logs/dev.log) [<a href='function.fopen'>function.fopen</a>]: failed to open stream: Permission denied' in /home/demo/demo/app/cache/dev/classes.php:5260\nStack trace:\n#0 /home/demo/demo/app/cache/dev/classes.php(5200): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /home/demo/demo/app/cache/dev/classes.php(5647): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /home/demo/demo/app/cache/dev/classes.php(5718): Monolog\\Logger->addRecord(500, 'Uncaught Except...', Array)\n#3 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(490): Monolog\\Logger->log('critical', 'Uncaught Except...', Array)\n#4 [internal function]: Symfony\\Component\\Debug\\ErrorHandler->handleException(Object(UnexpectedValueException))\n#5 {main}\n  thrown in /home/demo/demo/app/cache/dev/classes.php on line 5260
[Mon Sep 07 05:28:15 2015] [error] [client 108.14.46.233] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/home/demo/demo/app/logs/dev.log" could not be opened: fopen(/home/demo/demo/app/logs/dev.log) [<a href='function.fopen'>function.fopen</a>]: failed to open stream: Permission denied' in /home/demo/demo/app/cache/dev/classes.php:5260\nStack trace:\n#0 /home/demo/demo/app/cache/dev/classes.php(5200): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /home/demo/demo/app/cache/dev/classes.php(5647): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /home/demo/demo/app/cache/dev/classes.php(5718): Monolog\\Logger->addRecord(500, 'Fatal Error: Un...', Array)\n#3 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(490): Monolog\\Logger->log('critical', 'Fatal Error: Un...', Array)\n#4 /home/demo/demo/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php(565): Symfony\\Component\\Debug\\ErrorHandler->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#5 [inter in /home/demo/demo/app/cache/dev/classes.php on line 5260
[Mon Sep 07 05:41:32 2015] [error] [client 108.14.46.233] PHP Fatal error:  Class 'AppBundle\\Entity\\ArrayCollection' not found in /home/demo/demo/src/AppBundle/Entity/Portfolio.php on line 38, referer: http://demo.waleup.com/app_dev.php/portfolio/
[Mon Sep 07 05:42:29 2015] [error] [client 108.14.46.233] PHP Parse error:  syntax error, unexpected T_CLASS, expecting ',' or ';' in /home/demo/demo/src/AppBundle/Entity/Portfolio.php on line 11, referer: http://demo.waleup.com/app_dev.php/portfolio/
[Mon Sep 07 06:14:41 2015] [error] [client 108.14.46.233] PHP Warning:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Undefined variable: authenticationUtils' in /home/demo/demo/src/AppBundle/Controller/SecurityController.php:17\nStack trace:\n#0 /home/demo/demo/src/AppBundle/Controller/SecurityController.php(17): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined varia...', '/home/demo/demo...', 17, Array)\n#1 [internal function]: AppBundle\\Controller\\SecurityController->loginAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /home/demo/demo/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /home/demo/demo/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /home/demo/demo/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/demo/demo/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17
[Mon Sep 07 06:14:41 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getLastAuthenticationError() on a non-object in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17
[Mon Sep 07 06:14:42 2015] [error] [client 108.14.46.233] PHP Warning:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Undefined variable: authenticationUtils' in /home/demo/demo/src/AppBundle/Controller/SecurityController.php:17\nStack trace:\n#0 /home/demo/demo/src/AppBundle/Controller/SecurityController.php(17): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined varia...', '/home/demo/demo...', 17, Array)\n#1 [internal function]: AppBundle\\Controller\\SecurityController->loginAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /home/demo/demo/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /home/demo/demo/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /home/demo/demo/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/demo/demo/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:14:42 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getLastAuthenticationError() on a non-object in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:14:44 2015] [error] [client 108.14.46.233] PHP Warning:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Undefined variable: authenticationUtils' in /home/demo/demo/src/AppBundle/Controller/SecurityController.php:17\nStack trace:\n#0 /home/demo/demo/src/AppBundle/Controller/SecurityController.php(17): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined varia...', '/home/demo/demo...', 17, Array)\n#1 [internal function]: AppBundle\\Controller\\SecurityController->loginAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /home/demo/demo/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /home/demo/demo/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /home/demo/demo/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/demo/demo/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:14:44 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getLastAuthenticationError() on a non-object in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:14:45 2015] [error] [client 108.14.46.233] PHP Warning:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Undefined variable: authenticationUtils' in /home/demo/demo/src/AppBundle/Controller/SecurityController.php:17\nStack trace:\n#0 /home/demo/demo/src/AppBundle/Controller/SecurityController.php(17): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined varia...', '/home/demo/demo...', 17, Array)\n#1 [internal function]: AppBundle\\Controller\\SecurityController->loginAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /home/demo/demo/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /home/demo/demo/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /home/demo/demo/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/demo/demo/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:14:45 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getLastAuthenticationError() on a non-object in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:14:47 2015] [error] [client 108.14.46.233] PHP Warning:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Undefined variable: authenticationUtils' in /home/demo/demo/src/AppBundle/Controller/SecurityController.php:17\nStack trace:\n#0 /home/demo/demo/src/AppBundle/Controller/SecurityController.php(17): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined varia...', '/home/demo/demo...', 17, Array)\n#1 [internal function]: AppBundle\\Controller\\SecurityController->loginAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /home/demo/demo/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /home/demo/demo/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /home/demo/demo/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/demo/demo/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:14:47 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getLastAuthenticationError() on a non-object in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:14:49 2015] [error] [client 108.14.46.233] PHP Warning:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Undefined variable: authenticationUtils' in /home/demo/demo/src/AppBundle/Controller/SecurityController.php:17\nStack trace:\n#0 /home/demo/demo/src/AppBundle/Controller/SecurityController.php(17): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined varia...', '/home/demo/demo...', 17, Array)\n#1 [internal function]: AppBundle\\Controller\\SecurityController->loginAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /home/demo/demo/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /home/demo/demo/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /home/demo/demo/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/demo/demo/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:14:49 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getLastAuthenticationError() on a non-object in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:14:52 2015] [error] [client 108.14.46.233] PHP Warning:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Undefined variable: authenticationUtils' in /home/demo/demo/src/AppBundle/Controller/SecurityController.php:17\nStack trace:\n#0 /home/demo/demo/src/AppBundle/Controller/SecurityController.php(17): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined varia...', '/home/demo/demo...', 17, Array)\n#1 [internal function]: AppBundle\\Controller\\SecurityController->loginAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /home/demo/demo/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /home/demo/demo/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /home/demo/demo/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/demo/demo/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:14:52 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getLastAuthenticationError() on a non-object in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:14:53 2015] [error] [client 108.14.46.233] PHP Warning:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Undefined variable: authenticationUtils' in /home/demo/demo/src/AppBundle/Controller/SecurityController.php:17\nStack trace:\n#0 /home/demo/demo/src/AppBundle/Controller/SecurityController.php(17): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined varia...', '/home/demo/demo...', 17, Array)\n#1 [internal function]: AppBundle\\Controller\\SecurityController->loginAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /home/demo/demo/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /home/demo/demo/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /home/demo/demo/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/demo/demo/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:14:53 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getLastAuthenticationError() on a non-object in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:14:56 2015] [error] [client 108.14.46.233] PHP Warning:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Undefined variable: authenticationUtils' in /home/demo/demo/src/AppBundle/Controller/SecurityController.php:17\nStack trace:\n#0 /home/demo/demo/src/AppBundle/Controller/SecurityController.php(17): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined varia...', '/home/demo/demo...', 17, Array)\n#1 [internal function]: AppBundle\\Controller\\SecurityController->loginAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /home/demo/demo/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /home/demo/demo/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /home/demo/demo/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/demo/demo/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:14:56 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getLastAuthenticationError() on a non-object in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:15:40 2015] [error] [client 108.14.46.233] PHP Warning:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Undefined variable: authenticationUtils' in /home/demo/demo/src/AppBundle/Controller/SecurityController.php:19\nStack trace:\n#0 /home/demo/demo/src/AppBundle/Controller/SecurityController.php(19): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined varia...', '/home/demo/demo...', 19, Array)\n#1 [internal function]: AppBundle\\Controller\\SecurityController->loginAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /home/demo/demo/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /home/demo/demo/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /home/demo/demo/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/demo/demo/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 19
[Mon Sep 07 06:15:40 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getLastUsername() on a non-object in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 19
[Mon Sep 07 06:15:41 2015] [error] [client 108.14.46.233] PHP Warning:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Undefined variable: authenticationUtils' in /home/demo/demo/src/AppBundle/Controller/SecurityController.php:19\nStack trace:\n#0 /home/demo/demo/src/AppBundle/Controller/SecurityController.php(19): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined varia...', '/home/demo/demo...', 19, Array)\n#1 [internal function]: AppBundle\\Controller\\SecurityController->loginAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /home/demo/demo/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /home/demo/demo/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /home/demo/demo/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/demo/demo/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 19, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:15:41 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getLastUsername() on a non-object in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 19, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:15:43 2015] [error] [client 108.14.46.233] PHP Warning:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Undefined variable: authenticationUtils' in /home/demo/demo/src/AppBundle/Controller/SecurityController.php:19\nStack trace:\n#0 /home/demo/demo/src/AppBundle/Controller/SecurityController.php(19): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined varia...', '/home/demo/demo...', 19, Array)\n#1 [internal function]: AppBundle\\Controller\\SecurityController->loginAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /home/demo/demo/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /home/demo/demo/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /home/demo/demo/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/demo/demo/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 19, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:15:43 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getLastUsername() on a non-object in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 19, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:15:44 2015] [error] [client 108.14.46.233] PHP Warning:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Undefined variable: authenticationUtils' in /home/demo/demo/src/AppBundle/Controller/SecurityController.php:19\nStack trace:\n#0 /home/demo/demo/src/AppBundle/Controller/SecurityController.php(19): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined varia...', '/home/demo/demo...', 19, Array)\n#1 [internal function]: AppBundle\\Controller\\SecurityController->loginAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /home/demo/demo/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /home/demo/demo/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /home/demo/demo/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/demo/demo/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 19, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:15:44 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getLastUsername() on a non-object in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 19, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:15:47 2015] [error] [client 108.14.46.233] PHP Warning:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Undefined variable: authenticationUtils' in /home/demo/demo/src/AppBundle/Controller/SecurityController.php:19\nStack trace:\n#0 /home/demo/demo/src/AppBundle/Controller/SecurityController.php(19): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined varia...', '/home/demo/demo...', 19, Array)\n#1 [internal function]: AppBundle\\Controller\\SecurityController->loginAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /home/demo/demo/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /home/demo/demo/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /home/demo/demo/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/demo/demo/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 19, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:15:47 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getLastUsername() on a non-object in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 19, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:16:28 2015] [error] [client 108.14.46.233] PHP Warning:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Undefined variable: authenticationUtils' in /home/demo/demo/src/AppBundle/Controller/SecurityController.php:19\nStack trace:\n#0 /home/demo/demo/src/AppBundle/Controller/SecurityController.php(19): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined varia...', '/home/demo/demo...', 19, Array)\n#1 [internal function]: AppBundle\\Controller\\SecurityController->loginAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /home/demo/demo/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /home/demo/demo/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /home/demo/demo/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/demo/demo/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 19
[Mon Sep 07 06:16:28 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getLastUsername() on a non-object in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17
[Mon Sep 07 06:16:29 2015] [error] [client 108.14.46.233] PHP Warning:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Undefined variable: authenticationUtils' in /home/demo/demo/src/AppBundle/Controller/SecurityController.php:19\nStack trace:\n#0 /home/demo/demo/src/AppBundle/Controller/SecurityController.php(19): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined varia...', '/home/demo/demo...', 19, Array)\n#1 [internal function]: AppBundle\\Controller\\SecurityController->loginAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /home/demo/demo/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /home/demo/demo/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /home/demo/demo/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/demo/demo/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 19, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:16:29 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getLastUsername() on a non-object in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:16:37 2015] [error] [client 108.14.46.233] PHP Warning:  Uncaught exception 'Symfony\\Component\\Debug\\Exception\\ContextErrorException' with message 'Notice: Undefined variable: authenticationUtils' in /home/demo/demo/src/AppBundle/Controller/SecurityController.php:19\nStack trace:\n#0 /home/demo/demo/src/AppBundle/Controller/SecurityController.php(19): Symfony\\Component\\Debug\\ErrorHandler->handleError(8, 'Undefined varia...', '/home/demo/demo...', 19, Array)\n#1 [internal function]: AppBundle\\Controller\\SecurityController->loginAction(Object(Symfony\\Component\\HttpFoundation\\Request))\n#2 /home/demo/demo/app/bootstrap.php.cache(3109): call_user_func_array(Array, Array)\n#3 /home/demo/demo/app/bootstrap.php.cache(3071): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /home/demo/demo/app/bootstrap.php.cache(3222): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /home/demo/demo/app/bootstrap.php.cache(2444): Symfony\\Component\\HttpKernel\\DependencyInjection in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 19, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 06:16:37 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getLastUsername() on a non-object in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 17, referer: http://demo.waleup.com/app_dev.php/login
[Mon Sep 07 07:17:03 2015] [error] [client 108.14.46.233] PHP Fatal error:  Class 'AppBundle\\Controller\\User' not found in /home/demo/demo/src/AppBundle/Controller/SecurityController.php on line 34
[Mon Sep 07 08:23:48 2015] [error] [client 108.14.46.233] PHP Fatal error:  Call to a member function getQuotesList() on a non-object in /home/demo/demo/src/AppBundle/Entity/Stock.php on line 98, referer: http://demo.waleup.com/app_dev.php/stock/
[Mon Sep 07 08:29:16 2015] [error] [client 108.14.46.233] PHP Fatal error:  Class 'AppBundle\\Entity\\Date' not found in /home/demo/demo/src/AppBundle/Entity/Stock.php on line 107, referer: http://demo.waleup.com/app_dev.php/stock/
[Mon Sep 07 08:32:00 2015] [error] [client 108.14.46.233] PHP Fatal error:  Class 'AppBundle\\Entity\\DateTime' not found in /home/demo/demo/src/AppBundle/Entity/Stock.php on line 107, referer: http://demo.waleup.com/app_dev.php/stock/
[Mon Sep 07 08:35:15 2015] [error] [client 108.14.46.233] PHP Fatal error:  Class 'AppBundle\\Entity\\DateTime' not found in /home/demo/demo/src/AppBundle/Entity/Stock.php on line 107
